#!/bin/bash

curl -u 'mannen0' https://api.github.com/user/repos -d "{\"name\":\"$1\"}"

# curl -u 'USER' https://api.github.com/user/repos -d '{"name":"REPO"}'
# git remote add origin git@github.com:USER/REPO.git
# git push origin master
